# Site settings
title: Dolcey Mendoza Jr 
email: dolceymendozajr@gmail.com
description: I'm Software Engineering student who wants to create cool stuff.
baseurl: "https://dolceymendozajr.github.io/" # the subpath of your site, e.g. /blog/
url: "https://dolceymendozajr.github.io/" # the base hostname & protocol for your site

twitter_username: dolceymendozajr
github_username: dolceymendozajr

# Build settings
markdown: kramdown
